Draft
zaz600/brute-force-protector pull request #1
Opened 2021-02-02 17:21 UTC by zaz600

2021-02-07 09:58 UTC, farir1408 requested changes

2021-02-07 09:58 UTC, farir1408 commented on cmd/bruteforceprotector/main.go
> +	bfProtector := bruteforceprotector.NewBruteForceProtector(10, 100, 1000)
Очень много скаляров, может стоит их вынести в константы, или в конфиг? Тем самым сделаем их более понятными, что они делают и зачем нужны.

2021-02-07 09:58 UTC, farir1408 commented on internal/bruteforceprotector/service.go
> +	blackList accesslist.AccessList
Интерфейс и реализация лежат в одном пакете тем самым делая зависимость от реализации, давайте вынесем интерфейс сюда, или в отдельный пакет.

2021-02-07 10:00 UTC, farir1408 commented
Здравствуйте!

Отличное начало, есть пара небольших замечаний, думаю к следующей проверке поправите. Жду остальные пункты, и давайте добавим в readme описание сервиса, можно скопировать из описания дз.

2021-02-16 19:59 UTC, zaz600 commented
Улучшать код можно было бы бесконечно, не будь он учебным.
Оглядываясь назад, я бы переделал ratelimiter на Redis, но, что выросло, то выросло :)

2021-02-22 09:38 UTC, farir1408 approved these changes

2021-02-22 09:38 UTC, farir1408 commented on cmd/bp-cli/main.go
> +	"github.com/urfave/cli/v2"
Ещё можно посмотреть на вот эту библиотеку, она довольно распространённая: https://github.com/spf13/cobra

2021-02-22 09:38 UTC, farir1408 commented on internal/accesslist/memoryaccesslist/memory_access_list.go
> +func NewMemoryAccessList() accesslist.AccessList {
Лучше возвращать реализацию, а уже там где она нужна ограничивать её интерфейсом. https://github.com/golang/go/wiki/CodeReviewComments#interfaces

2021-02-22 09:38 UTC, farir1408 commented on internal/grpc/server.go
> +	go func() {
Обработчик лучше вынести в main, здесь только запуск листенегра.

2021-02-22 09:40 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение проектной работы, отличный результат.
Принято 15/15. По поводу рейтлимита на редисе - это уже подходит как продакшен решение, в качестве учебного варианта подходит и собственная реализация.

2021-02-22 10:29 UTC, merged